letter done 62.jpg
Apnasite/letter-assignments pull request #16
Opened 2024-07-23 07:44 UTC by Bhosle07

2024-08-01 04:20 UTC, laxmikant-gaykhee requested changes
-Add **style.css** in **css** folder 
-Add **images** in **img** folder
-Add **preview.html** 
-**index.html** in this file give only **background div**

2024-08-05 10:11 UTC, laxmikant-gaykhee approved these changes

2024-09-18 17:07 UTC, KalpeshApnasite requested changes
css folder name must be in lower case

2024-09-18 17:20 UTC, KalpeshApnasite requested changes

2024-09-18 17:20 UTC, KalpeshApnasite commented on SubmittedAssignments/Bhosle_Mahesh_letter/.vscode/settings.json
remove this folder

2024-09-18 17:20 UTC, KalpeshApnasite commented on SubmittedAssignments/Bhosle_Mahesh_letter/CSS/style.css
> +    border: 3px solid rgb(88, 191, 101);
do not use px

2024-09-20 16:39 UTC, closed without merging